import { Header } from "@/components/shared/header";
import { Nunito } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

//Описание для SEO
export const metadata: Metadata = {
  title: "Pizz-fullstack | Главная",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <main className={"min-h-screen"}>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
